eyetracker:
  address: 100.1.1.1
  dot_size: 0.1
  options:
    active_eye: left
    automatic_calibration_pacing: 1000
    autothreshold_click: true
    autothreshold_repeat: true
    binocular_enabled: false
    calibration_type: HV9
    enable_automatic_calibration: true
    enable_camera_position_detect: true
    enable_search_limits: true
    file_event_filter: LEFT,RIGHT,FIXATION,SACCADE,BLINK,MESSAGE,BUTTON,INPUT
    heuristic_filter: 2
    link_event_filter: LEFT,RIGHT,FIXATION,SACCADE,BLINK,BUTTON
    link_sample_data: LEFT,RIGHT,GAZE,GAZERES,AREA,STATUS,HTARGET
    pupil_size_diameter: true
    sample_rate: 1000
    track_search_limits: true
    x_gaze_constraint: AUTO
    y_gaze_constraint: AUTO
fixation_cross:
  bg:
  - 1.0
  - 1.0
  - 1.0
  inner_radius: 0.2
  outer_radius: 0.4
input:
  response_button_left: z
  response_button_right: m
monitor:
  distance: 50
  gamma: 1
  name: default
  width: 60
mouse:
  visible: false
mri:
  TA: 2.0
  TR: 2.0
  simulate: false
  skip: 0
  sound: false
  sync: t
  volumes: 10
  warmup_trs: 0
preferences:
  general:
    audioLib: sounddevice
    units: deg
stimulus:
  font: Agathodaimon
  font_fn: ./lib/Glagolitsa.ttf
  height: 3
  line_color: white
  line_width: 10
  rect_line_width: 10
  text_height: 3
  units: deg
  width: 3
  x_pos:
  - -4
  - 4
text:
  feedback_y_pos:
  - 1.25
  - -1.25
  - 0
  height: 1
  units: deg
  wrap_width: 25
window:
  color:
  - 0
  - 0
  - 0
  fullscr: true
  pos:
  - 0
  - 0
  size:
  - 2560
  - 1440
  useFBO: true
  useRetina: true
  waitBlanking: true
